// SA Plant Library — pure data + helpers (no components, Fast-Refresh
// friendly). Feeds the "Plants near you" home card, the Explore Plants tab,
// and the Magazine's plant articles.
//
// Not exhaustive like the SA bird library (~375 species) — a careful, solid
// set of well-known South African garden, indigenous, tree, succulent and
// fynbos species, region-tagged so the same rotation mechanism the birds use
// (weekly hash-seeded watch-list) can serve a Potchefstroom-area default and
// a Cape Town / fynbos variant during the Cape Town Special Week.

export const PLANT_CATEGORIES = [
  'Flowers',
  'Trees',
  'Succulents',
  'Fynbos',
  'Garden Plants',
  'Indigenous',
]

// regions: 'potch' = common on the Highveld / in Potchefstroom-area gardens,
// 'capetown' = fynbos / Western Cape specialities. Most indigenous species
// that are also widely garden-grown carry both tags.
export const SA_PLANT_LIBRARY = [
  {
    id: 'king-protea',
    commonName: 'King Protea',
    afrikaansName: 'Koningsprotea',
    scientificName: 'Protea cynaroides',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Autumn to winter',
    funFact:
      "South Africa's national flower — its flower head can grow up to 30cm wide, the largest of any protea species.",
    whereFound: 'Fynbos slopes and mountain fynbos across the Western Cape, especially the Cape Peninsula.',
    careTips: 'Full sun, very well-drained acidic soil, and no phosphate fertiliser — sandy soil mimics its native fynbos best.',
  },
  {
    id: 'sugarbush',
    commonName: 'Common Sugarbush',
    afrikaansName: 'Suikerbos',
    scientificName: 'Protea repens',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Most of the year, peaking in autumn and winter',
    funFact: 'One of the most widespread proteas — its nectar-rich flowers are a favourite of sunbirds and Cape sugarbirds.',
    whereFound: 'Fynbos across the Western and Eastern Cape mountains.',
    careTips: 'Full sun, sandy well-drained soil, drought-tolerant once established.',
  },
  {
    id: 'pincushion',
    commonName: 'Pincushion Protea',
    afrikaansName: 'Speldekussing',
    scientificName: 'Leucospermum cordifolium',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Late winter to spring',
    funFact: 'Named for its round flower heads covered in curved styles that look like a pincushion full of pins.',
    whereFound: 'Fynbos on the Cape south coast mountains.',
    careTips: 'Needs excellent drainage and full sun — very sensitive to wet, heavy soil.',
  },
  {
    id: 'silver-tree',
    commonName: 'Silver Tree',
    afrikaansName: 'Silwerboom',
    scientificName: 'Leucadendron argenteum',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Winter',
    funFact: 'Its silky silver leaves are covered in fine hairs that reflect sunlight — found naturally almost nowhere except Table Mountain.',
    whereFound: 'Table Mountain and the Cape Peninsula, almost exclusively.',
    careTips: 'Full sun, sandy acidic soil, and cool coastal air — notoriously difficult to grow away from the Cape.',
  },
  {
    id: 'watsonia',
    commonName: 'Watsonia',
    afrikaansName: 'Suurkanol',
    scientificName: 'Watsonia borbonica',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Spring to early summer',
    funFact: 'A tall, showy relative of the gladiolus that carpets fynbos slopes with pink spikes after fire.',
    whereFound: 'Fynbos slopes across the Western Cape.',
    careTips: 'Full sun, well-drained soil, dies back to a corm in summer — very drought tolerant once dormant.',
  },
  {
    id: 'freesia',
    commonName: 'Freesia',
    afrikaansName: 'Freesia',
    scientificName: 'Freesia refracta',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Late winter to early spring',
    funFact: 'One of the most fragrant flowers in the world, and the ancestor of nearly every freesia grown in gardens globally.',
    whereFound: 'Sandy flats and lower slopes across the Western Cape.',
    careTips: 'Full sun, well-drained soil, plant corms in autumn for a spring bloom.',
  },
  {
    id: 'agapanthus',
    commonName: 'Agapanthus',
    afrikaansName: 'Bloulelie',
    scientificName: 'Agapanthus africanus',
    category: 'Garden Plants',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Summer',
    funFact: 'Its name comes from Greek for "love flower" — one of South Africa’s most exported garden plants worldwide.',
    whereFound: 'Rocky slopes in the Western Cape natively, but grown in gardens right across the country.',
    careTips: 'Full sun to light shade, tolerant of poor soil and drought once established — a very forgiving garden plant.',
  },
  {
    id: 'clivia',
    commonName: 'Clivia',
    afrikaansName: 'Boslelie',
    scientificName: 'Clivia miniata',
    category: 'Indigenous',
    regions: ['potch'],
    bloomSeason: 'Late winter to spring',
    funFact: 'Thrives in deep shade where almost nothing else flowers — a favourite for shady gardens across South Africa.',
    whereFound: 'Shaded forest understorey from the Eastern Cape through KwaZulu-Natal into Mpumalanga and Limpopo.',
    careTips: 'Deep shade, well-drained soil, and don’t overwater — it prefers to dry out between waterings.',
  },
  {
    id: 'bird-of-paradise',
    commonName: 'Bird of Paradise',
    afrikaansName: 'Kraanvoëlblom',
    scientificName: 'Strelitzia reginae',
    category: 'Garden Plants',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Most of the year, peaking in winter and spring',
    funFact: 'Its orange and blue flower is shaped to let sunbirds land on it and pollinate it while feeding on the nectar.',
    whereFound: 'Native to the Eastern Cape, but grown as a garden and street plant across South Africa.',
    careTips: 'Full sun, rich well-drained soil, and regular watering in summer for the best flowering.',
  },
  {
    id: 'wild-banana',
    commonName: 'Wild Banana',
    afrikaansName: 'Wilde-piesang',
    scientificName: 'Strelitzia nicolai',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Most of the year',
    funFact: "The giant, tree-sized relative of the Bird of Paradise — can grow up to 10 metres tall, despite not being a true banana.",
    whereFound: 'Coastal forest from the Eastern Cape to KwaZulu-Natal, widely planted as a garden tree elsewhere.',
    careTips: 'Full sun to part shade, rich soil, and regular water — a fast-growing architectural garden tree.',
  },
  {
    id: 'arum-lily',
    commonName: 'Arum Lily',
    afrikaansName: 'Varkoor',
    scientificName: 'Zantedeschia aethiopica',
    category: 'Indigenous',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Spring to summer',
    funFact: 'The elegant white "flower" is actually a leaf-like bract wrapped around the true, tiny flowers on the central spike.',
    whereFound: 'Damp ground and streambanks across most of South Africa.',
    careTips: 'Full sun to part shade, likes consistently moist soil — thrives at the edge of a pond or damp corner.',
  },
  {
    id: 'red-hot-poker',
    commonName: 'Red Hot Poker',
    afrikaansName: 'Vuurpyl',
    scientificName: 'Kniphofia uvaria',
    category: 'Flowers',
    regions: ['potch'],
    bloomSeason: 'Summer to autumn',
    funFact: 'Its glowing orange-to-yellow flower spikes are a magnet for sunbirds, which feed on the nectar tube by tube from the bottom up.',
    whereFound: 'Grassland and rocky slopes across the Eastern Cape and KwaZulu-Natal.',
    careTips: 'Full sun, well-drained soil, very hardy and drought tolerant once established.',
  },
  {
    id: 'wild-dagga',
    commonName: 'Wild Dagga',
    afrikaansName: 'Wildedagga',
    scientificName: 'Leonotis leonurus',
    category: 'Flowers',
    regions: ['potch'],
    bloomSeason: 'Late summer to autumn',
    funFact: 'Its shaggy orange flowers grow in tidy whorls up the stem and are a favourite of sunbirds — despite the name, it is unrelated to cannabis.',
    whereFound: 'Grassland and rocky slopes across much of South Africa, including the Highveld.',
    careTips: 'Full sun, tolerates poor soil, very drought hardy once established.',
  },
  {
    id: 'barberton-daisy',
    commonName: 'Barberton Daisy',
    afrikaansName: 'Barbertonse madeliefie',
    scientificName: 'Gerbera jamesonii',
    category: 'Flowers',
    regions: ['potch'],
    bloomSeason: 'Spring to autumn',
    funFact: "Discovered near Barberton in Mpumalanga in the 1880s, it's the wild ancestor of almost every gerbera sold in flower shops worldwide.",
    whereFound: 'Rocky grassland slopes in Mpumalanga and neighbouring provinces.',
    careTips: 'Full sun to light shade, well-drained soil — a reliable, colourful garden and pot plant.',
  },
  {
    id: 'plumbago',
    commonName: 'Cape Plumbago',
    afrikaansName: 'Blousyselbos',
    scientificName: 'Plumbago auriculata',
    category: 'Garden Plants',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Spring through to autumn',
    funFact: 'Its soft powder-blue flowers are a favourite nectar stop for butterflies, especially the Common Blue.',
    whereFound: 'Forest margins and thicket across the Eastern Cape, widely grown as a hedge elsewhere.',
    careTips: 'Full sun to part shade, drought tolerant, prune hard after winter to keep it flowering well.',
  },
  {
    id: 'cape-honeysuckle',
    commonName: 'Cape Honeysuckle',
    afrikaansName: 'Kaapse kanferfoelie',
    scientificName: 'Tecoma capensis',
    category: 'Garden Plants',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Most of the year, peaking in autumn and winter',
    funFact: 'Its tubular orange flowers are one of the most reliable nectar sources for sunbirds through the coldest months.',
    whereFound: 'Forest margins and coastal scrub across the Eastern Cape and KwaZulu-Natal.',
    careTips: 'Full sun to part shade, tolerant of poor soil, makes an excellent bird-friendly hedge.',
  },
  {
    id: 'namaqualand-daisy',
    commonName: 'Namaqualand Daisy',
    afrikaansName: 'Namakwalandse madeliefie',
    scientificName: 'Dimorphotheca sinuata',
    category: 'Flowers',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Late winter to early spring',
    funFact: 'After good winter rains, these daisies carpet entire hillsides in Namaqualand in one of the world’s great wildflower displays.',
    whereFound: 'Semi-arid Namaqualand region of the Northern and Western Cape.',
    careTips: 'Full sun, sandy well-drained soil, sow seed in autumn for a spring show.',
  },
  {
    id: 'vygie',
    commonName: 'Vygie',
    afrikaansName: 'Vygie',
    scientificName: 'Lampranthus spectabilis',
    category: 'Succulents',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Spring',
    funFact: 'Its jewel-bright flowers only open fully in sunshine and close again on cloudy days and at night.',
    whereFound: 'Rocky and sandy slopes across the Western Cape.',
    careTips: 'Full sun, very well-drained soil, extremely drought tolerant — perfect for a rockery.',
  },
  {
    id: 'bitter-aloe',
    commonName: 'Bitter Aloe',
    afrikaansName: 'Bergaalwyn',
    scientificName: 'Aloe ferox',
    category: 'Succulents',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Winter',
    funFact: 'Its bitter sap has been harvested for centuries as a traditional remedy, and its tall orange flower spikes feed sunbirds through the coldest months.',
    whereFound: 'Dry, rocky slopes across the Eastern and Western Cape.',
    careTips: 'Full sun, extremely well-drained soil, waters sparingly — very drought tolerant once established.',
  },
  {
    id: 'spekboom',
    commonName: 'Spekboom',
    afrikaansName: 'Spekboom',
    scientificName: 'Portulacaria afra',
    category: 'Succulents',
    regions: ['potch'],
    bloomSeason: 'Late summer',
    funFact: "One of the most efficient carbon-absorbing plants in the world — a single hectare of spekboom thicket can lock away a surprising amount of carbon each year.",
    whereFound: 'Thicket vegetation in the Eastern Cape, widely planted as a hedge across South Africa.',
    careTips: 'Full sun to part shade, extremely drought tolerant, grows easily from a simple cutting.',
  },
  {
    id: 'century-plant',
    commonName: 'Century Plant',
    afrikaansName: 'Eeuplant',
    scientificName: 'Agave americana',
    category: 'Succulents',
    regions: ['potch'],
    bloomSeason: 'Once, after many years, then the rosette dies',
    funFact: 'Flowers only once in its life, sending up a towering flower spike several metres tall before the main rosette dies back.',
    whereFound: 'Originally from Mexico, but a common, tough garden and boundary plant across South Africa.',
    careTips: 'Full sun, very well-drained soil, essentially indestructible once established — handle the sharp leaf tips with care.',
  },
  {
    id: 'karee',
    commonName: 'Karee',
    afrikaansName: 'Karee',
    scientificName: 'Searsia lancea',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Late winter, small inconspicuous flowers',
    funFact: 'A tough, evergreen tree often planted for shade on Highveld farms and gardens — its narrow willow-like leaves cast dappled shade.',
    whereFound: 'Widespread across the drier interior of South Africa, including the Highveld.',
    careTips: 'Full sun, tolerant of poor soil and drought once established — a reliable, low-maintenance shade tree.',
  },
  {
    id: 'wild-olive',
    commonName: 'Wild Olive',
    afrikaansName: 'Olienhout',
    scientificName: 'Olea europaea subsp. africana',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Spring, small inconspicuous flowers',
    funFact: 'The indigenous cousin of the Mediterranean olive tree — its small fruit is a favourite of fruit-eating birds.',
    whereFound: 'Widespread across South Africa, from the Cape through to the Highveld.',
    careTips: 'Full sun, tolerant of poor soil, slow-growing but very hardy and long-lived.',
  },
  {
    id: 'yellowwood',
    commonName: 'Real Yellowwood',
    afrikaansName: 'Opregte geelhout',
    scientificName: 'Podocarpus latifolius',
    category: 'Trees',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Spring, small inconspicuous flowers',
    funFact: "South Africa's national tree — an ancient conifer that can live for many centuries in the country's indigenous forests.",
    whereFound: 'Indigenous forest patches from the Cape through to Limpopo, including the Knysna forests.',
    careTips: 'Part shade when young, tolerant of full sun once established, slow-growing and long-lived.',
  },
  {
    id: 'buffalo-thorn',
    commonName: 'Buffalo Thorn',
    afrikaansName: "Blinkblaar-wag-'n-bietjie",
    scientificName: 'Ziziphus mucronata',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Summer, small inconspicuous flowers',
    funFact: 'Its Afrikaans name means "shiny-leaf wait-a-bit," after its hooked thorns — a culturally significant tree in many South African traditions.',
    whereFound: 'Widespread across the drier bushveld and Highveld regions of South Africa.',
    careTips: 'Full sun, tolerant of poor soil and drought, thorny — best planted away from pathways.',
  },
  {
    id: 'jacaranda',
    commonName: 'Jacaranda',
    afrikaansName: 'Jacaranda',
    scientificName: 'Jacaranda mimosifolia',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Spring (October–November)',
    funFact: 'Not indigenous to South Africa, but so widely planted that entire streets across Pretoria and the Highveld turn purple every spring.',
    whereFound: 'Streets, parks and gardens across South Africa’s interior towns and cities.',
    careTips: 'Full sun, deep watering while young, sheds a carpet of purple flowers that many towns sweep up each spring.',
  },
  {
    id: 'wild-garlic',
    commonName: 'Wild Garlic',
    afrikaansName: 'Wildeknoffel',
    scientificName: 'Tulbaghia violacea',
    category: 'Flowers',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Spring to autumn',
    funFact: 'Its leaves smell faintly of garlic when crushed and are sometimes used to season food, though it is grown mostly for its pretty mauve flower clusters.',
    whereFound: 'Rocky grassland across the eastern half of South Africa.',
    careTips: 'Full sun to light shade, tolerant of poor soil, very easy and reliable in a border.',
  },
  {
    id: 'cosmos',
    commonName: 'Cosmos',
    afrikaansName: 'Kosmos',
    scientificName: 'Cosmos bipinnatus',
    category: 'Flowers',
    regions: ['potch'],
    bloomSeason: 'Autumn (March–May)',
    funFact: 'Not indigenous — it arrived in horse feed during the Anglo-Boer War — but it has naturalised so thoroughly that Highveld roadsides turn pink and white with it every autumn.',
    whereFound: 'Roadsides and fields across the Free State, Mpumalanga and North West provinces.',
    careTips: 'Full sun, poor soil is fine, self-seeds freely once established.',
  },
  // ---- Batch 2 (2026-07-14): fynbos, indigenous trees, succulents, medicinal
  // and coastal species, expanding toward a fuller field guide. ----
  {
    id: 'fire-heath',
    commonName: 'Fire Heath',
    afrikaansName: 'Vuurheide',
    scientificName: 'Erica cerinthoides',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Most of the year, peaking after fire',
    funFact: 'One of the most fire-adapted fynbos plants — it flowers most profusely in the season right after a fynbos fire sweeps through.',
    whereFound: 'Fynbos across the Western and Eastern Cape mountains.',
    careTips: 'Full sun, acidic sandy soil, excellent drainage — like most ericas, resents phosphate fertiliser and wet roots.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Erica_cerinthoides_flower.JPG/500px-Erica_cerinthoides_flower.JPG',
  },
  {
    id: 'sunshine-conebush',
    commonName: 'Common Sunshine Conebush',
    afrikaansName: 'Geelbos',
    scientificName: 'Leucadendron salignum',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Winter to spring',
    funFact: 'Its central leaves flush bright yellow or red just before flowering — the "sunshine" that gives it its name.',
    whereFound: 'One of the most widespread fynbos shrubs, found across the Western Cape mountains and lowlands.',
    careTips: 'Full sun, well-drained acidic soil, drought-tolerant once established — avoid phosphate-rich fertiliser.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Leucadendron_salignum_female_Middelberg_pass_04.jpg/500px-Leucadendron_salignum_female_Middelberg_pass_04.jpg',
  },
  {
    id: 'horsetail-restio',
    commonName: 'Horsetail Restio',
    afrikaansName: 'Besemriet',
    scientificName: 'Elegia capensis',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Spring — grown mainly for its feathery foliage',
    funFact: 'A true fynbos restio, not a grass or reed — its jointed, feathery stems look remarkably like a horsetail.',
    whereFound: 'Streambanks and damp fynbos slopes across the Western Cape.',
    careTips: 'Full sun to light shade, likes consistently moist, well-drained soil near water.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Elegia_capensis_CHCH_2.JPG/500px-Elegia_capensis_CHCH_2.JPG',
  },
  {
    id: 'rose-pelargonium',
    commonName: 'Rose-scented Pelargonium',
    afrikaansName: 'Kusmalva',
    scientificName: 'Pelargonium capitatum',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Spring to summer',
    funFact: 'Its crushed leaves smell strongly of rose — used to flavour teas and as a source of geranium essential oil.',
    whereFound: 'Coastal dunes and sandy flats across the Western and Eastern Cape.',
    careTips: 'Full sun, sandy well-drained soil, very drought- and salt-tolerant — ideal for coastal gardens.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Pelargonium_capitatum1.jpg/500px-Pelargonium_capitatum1.jpg',
  },
  {
    id: 'blushing-bride',
    commonName: 'Blushing Bride',
    afrikaansName: 'Bruidjie',
    scientificName: 'Serruria florida',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Late winter to spring',
    funFact: 'Once thought extinct in the wild — its papery pink-and-white flower heads made it a favourite for bridal bouquets, hence the name.',
    whereFound: 'A rare fynbos endemic found naturally only in a few valleys near Franschhoek and Villiersdorp.',
    careTips: 'Full sun, sandy acidic soil, excellent drainage — notoriously tricky to grow away from its native valleys.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Serruria_florida.jpg/500px-Serruria_florida.jpg',
  },
  {
    id: 'red-disa',
    commonName: 'Red Disa',
    afrikaansName: 'Rooidisa',
    scientificName: 'Disa uniflora',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Late summer (January–March)',
    funFact: "South Africa's most famous orchid — its brilliant scarlet flower grows right in the spray of mountain streams and waterfalls.",
    whereFound: 'Perennial streams and waterfalls on Table Mountain and other Cape Peninsula mountains.',
    careTips: 'Needs permanently wet roots, cool running water, and light shade — extremely difficult outside its natural streamside habitat.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/RedDisa.jpg/500px-RedDisa.jpg',
  },
  {
    id: 'common-pagoda',
    commonName: 'Common Pagoda',
    afrikaansName: 'Trospagode',
    scientificName: 'Mimetes cucullatus',
    category: 'Fynbos',
    regions: ['capetown'],
    bloomSeason: 'Winter to spring',
    funFact: 'A favourite nectar stop for the Cape Sugarbird, whose long tail is perfectly suited to perching on its stacked, pagoda-like flower spikes.',
    whereFound: 'Fynbos slopes across the Cape Peninsula and southwestern Cape mountains.',
    careTips: 'Full sun, sandy acidic soil, excellent drainage — like most proteoids, dislikes phosphate fertiliser.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Mimetes_cucullatus.jpg/500px-Mimetes_cucullatus.jpg',
  },
  {
    id: 'fever-tree',
    commonName: 'Fever Tree',
    afrikaansName: 'Koorsboom',
    scientificName: 'Vachellia xanthophloea',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Spring to early summer',
    funFact: 'Its bark has a striking greenish-yellow, powdery sheen — early travellers mistakenly blamed it for the malaria fevers they caught nearby.',
    whereFound: 'Low-lying riverbanks and swampy ground in the bushveld — famously lines waterholes in the Kruger area.',
    careTips: 'Full sun, moist well-drained soil, fast-growing but frost-tender when young.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ngorongoro_Acacia_xanthophloea.jpg/500px-Ngorongoro_Acacia_xanthophloea.jpg',
  },
  {
    id: 'wild-fig',
    commonName: 'Common Wild Fig',
    afrikaansName: 'Gewone wildevy',
    scientificName: 'Ficus natalensis',
    category: 'Trees',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Year-round, inconspicuous flowers inside the fig',
    funFact: 'Often starts life as an epiphyte in the branches of another tree before sending roots to the ground and eventually engulfing its host.',
    whereFound: 'Forest margins and rocky outcrops across the eastern half of South Africa.',
    careTips: 'Full sun to part shade, adaptable to most soils, a fig wasp is needed for it to set true seed.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Ficus_natalensis.jpg/500px-Ficus_natalensis.jpg',
  },
  {
    id: 'marula',
    commonName: 'Marula',
    afrikaansName: 'Maroela',
    scientificName: 'Sclerocarya birrea',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Spring, before the new leaves appear',
    funFact: 'Its tart yellow fruit ferments so readily that elephants are famously (if exaggeratedly) said to get tipsy eating windfall marulas.',
    whereFound: 'Bushveld and lowveld across the northern and eastern parts of South Africa.',
    careTips: 'Full sun, deep well-drained soil, drought-tolerant once established, frost-tender when young.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Marula02.jpg/500px-Marula02.jpg',
  },
  {
    id: 'baobab',
    commonName: 'Baobab',
    afrikaansName: 'Kremetart',
    scientificName: 'Adansonia digitata',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Summer (November–December)',
    funFact: 'Can live for well over a thousand years and store thousands of litres of water in its swollen trunk to survive the dry season.',
    whereFound: 'Hot, low-lying bushveld in the far north of Limpopo, especially around the Soutpansberg.',
    careTips: 'Full sun, extremely well-drained soil, very slow-growing and frost-tender — best suited to warm, dry gardens.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Baobab_and_elephant%2C_Tanzania.jpg/500px-Baobab_and_elephant%2C_Tanzania.jpg',
  },
  {
    id: 'cape-ash',
    commonName: 'Cape Ash',
    afrikaansName: 'Essenhout',
    scientificName: 'Ekebergia capensis',
    category: 'Trees',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Spring, small fragrant flowers',
    funFact: 'A fast-growing forest tree whose small red fruit draws flocks of fruit-eating birds and even vervet monkeys.',
    whereFound: 'Indigenous forest and wooded ravines from the Cape through to Limpopo.',
    careTips: 'Full sun to part shade, moist well-drained soil, fast-growing and a good shade tree.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Ekebergia_capensis.JPG/500px-Ekebergia_capensis.JPG',
  },
  {
    id: 'cabbage-tree',
    commonName: 'Cabbage Tree',
    afrikaansName: 'Kiepersol',
    scientificName: 'Cussonia spicata',
    category: 'Trees',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Autumn, spikes of small greenish flowers',
    funFact: 'Its bold, umbrella-like leaves make it instantly recognisable on the bushveld skyline — a favourite roosting tree for birds of prey.',
    whereFound: 'Widespread across South Africa, from coastal forest to Highveld rocky outcrops.',
    careTips: 'Full sun to part shade, well-drained soil, fast-growing, tolerant of poor soil once established.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Cussonia_spicata%2C_habitus%2C_b%2C_Pretoria_NBT.jpg/500px-Cussonia_spicata%2C_habitus%2C_b%2C_Pretoria_NBT.jpg',
  },
  {
    id: 'sweet-thorn',
    commonName: 'Sweet Thorn',
    afrikaansName: 'Soetdoring',
    scientificName: 'Vachellia karroo',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Spring to summer, fragrant yellow pompom flowers',
    funFact: 'One of the most widespread trees in South Africa — its gum was traditionally chewed like a sweet, giving it its common name.',
    whereFound: 'Grassland, bushveld and riverbanks right across the interior of South Africa.',
    careTips: 'Full sun, tolerant of a wide range of soils and drought, thorny — best planted away from pathways.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Acacia_karroo%2C_habitus%2C_Jimmy_Aves_Park%2C_e.jpg/500px-Acacia_karroo%2C_habitus%2C_Jimmy_Aves_Park%2C_e.jpg',
  },
  {
    id: 'coral-tree',
    commonName: 'Common Coral Tree',
    afrikaansName: 'Gewone koraalboom',
    scientificName: 'Erythrina lysistemon',
    category: 'Trees',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Winter to early spring, before the new leaves',
    funFact: 'Its bare branches burst into brilliant scarlet flowers in winter — one of the first nectar sources for sunbirds after the cold months.',
    whereFound: 'Bushveld, coastal forest and gardens right across South Africa.',
    careTips: 'Full sun, well-drained soil, drought-tolerant once established, thorny bark when young.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Erythrina_lysistemon%2C_habitus%2C_Uniegeboutuine%2C_a.jpg/500px-Erythrina_lysistemon%2C_habitus%2C_Uniegeboutuine%2C_a.jpg',
  },
  {
    id: 'krantz-aloe',
    commonName: 'Krantz Aloe',
    afrikaansName: 'Krantzaalwyn',
    scientificName: 'Aloe arborescens',
    category: 'Succulents',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Winter',
    funFact: 'Its winter flame-orange flower spikes are a vital nectar source for sunbirds when almost nothing else is in bloom.',
    whereFound: 'Rocky slopes and cliff edges (krantzes) across much of South Africa.',
    careTips: 'Full sun, very well-drained soil, extremely drought-tolerant once established, frost-hardy for an aloe.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Aloe_arborescens_Compton.JPG/500px-Aloe_arborescens_Compton.JPG',
  },
  {
    id: 'mountain-aloe',
    commonName: 'Mountain Aloe',
    afrikaansName: 'Bergaalwyn',
    scientificName: 'Aloe marlothii',
    category: 'Succulents',
    regions: ['potch'],
    bloomSeason: 'Winter',
    funFact: 'One of the tallest single-stemmed aloes, with its distinctive slanted flower spikes all leaning toward the same side of the plant.',
    whereFound: 'Rocky bushveld hillsides across the northern and interior provinces.',
    careTips: 'Full sun, excellent drainage, extremely drought-tolerant once established.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Aloe_marlothii_subsp_marlothii%2C_habitus%2C_Melmoth.jpg/500px-Aloe_marlothii_subsp_marlothii%2C_habitus%2C_Melmoth.jpg',
  },
  {
    id: 'pigs-ear',
    commonName: "Pig's Ear",
    afrikaansName: 'Varkoor',
    scientificName: 'Cotyledon orbiculata',
    category: 'Succulents',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Summer, hanging orange bell flowers',
    funFact: 'Its thick, chalky-grey leaves are shaped just like a pig’s ear — a traditional folk remedy for warts and corns.',
    whereFound: 'Dry rocky slopes across most of South Africa, from the Cape to the Highveld.',
    careTips: 'Full sun, excellent drainage, very drought-tolerant — a classic easy-care succulent.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Cotyledon_orbiculata_-_pigs_ear_-_Cape_Point_-_South_Africa_2.JPG/500px-Cotyledon_orbiculata_-_pigs_ear_-_Cape_Point_-_South_Africa_2.JPG',
  },
  {
    id: 'jade-plant',
    commonName: 'Jade Plant',
    afrikaansName: 'Geluksplant',
    scientificName: 'Crassula ovata',
    category: 'Succulents',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Late winter, small starry white-pink flowers',
    funFact: 'Known as the "lucky plant" — a potted jade plant by the front door is a common good-luck tradition in South African homes.',
    whereFound: 'Rocky hillsides in the Eastern Cape, but grown as a houseplant and garden succulent nationwide.',
    careTips: 'Full sun to bright light, well-drained soil, let it dry out between waterings — very forgiving.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Crassula_ovata_700.jpg/500px-Crassula_ovata_700.jpg',
  },
  {
    id: 'living-stones',
    commonName: 'Living Stones',
    afrikaansName: 'Lewende klip',
    scientificName: 'Lithops karasmontana',
    category: 'Succulents',
    regions: ['potch'],
    bloomSeason: 'Autumn, daisy-like flowers open in the afternoon',
    funFact: 'Its paired leaves are camouflaged to look exactly like the pebbles around it — one of nature’s best examples of mimicry.',
    whereFound: 'Arid, stony ground across the Northern Cape and the wider semi-arid interior.',
    careTips: 'Full sun, gritty free-draining soil, water sparingly and only when clearly wrinkled — easy to kill with kindness.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Lithops_karasmontana_%22opalina%22.jpg/500px-Lithops_karasmontana_%22opalina%22.jpg',
  },
  {
    id: 'wild-iris',
    commonName: 'Wild Iris',
    afrikaansName: 'Wilde-iris',
    scientificName: 'Dietes grandiflora',
    category: 'Garden Plants',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Spring to autumn, each flower lasts only a day',
    funFact: 'Also called the fortnight lily — new flowers keep opening every couple of weeks for months on end, so it always looks freshly in bloom.',
    whereFound: 'Coastal forest margins in the Eastern Cape and KwaZulu-Natal, but grown in gardens nationwide.',
    careTips: 'Full sun to part shade, tolerant of poor soil and drought once established — a near-indestructible border plant.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Dietes_grandiflora_La_Brea.jpg/500px-Dietes_grandiflora_La_Brea.jpg',
  },
  {
    id: 'spur-flower',
    commonName: 'Large Spur Flower',
    afrikaansName: 'Spoorsalie',
    scientificName: 'Plectranthus ecklonii',
    category: 'Garden Plants',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Autumn, tall spikes of purple or white flowers',
    funFact: 'One of the few shade-loving plants that puts on a real flower show — its autumn flower spikes light up the shadiest corners of a garden.',
    whereFound: 'Forest margins from the Eastern Cape through KwaZulu-Natal, widely grown in shade gardens nationwide.',
    careTips: 'Part to full shade, moist well-drained soil, cut back hard after flowering to keep it compact.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Plectranthusecklonii.jpg/500px-Plectranthusecklonii.jpg',
  },
  {
    id: 'tree-wisteria',
    commonName: 'Tree Wisteria',
    afrikaansName: 'Vanwykshout',
    scientificName: 'Bolusanthus speciosus',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Spring (September–November), before the new leaves',
    funFact: 'Its hanging sprays of mauve, wisteria-like flowers make it one of the most spectacular flowering trees on the bushveld in early spring.',
    whereFound: 'Bushveld and rocky hillsides across the northern interior of South Africa.',
    careTips: 'Full sun, well-drained soil, drought-tolerant once established, slow-growing.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Bolusanthus_speciosus_%281%29.jpg/500px-Bolusanthus_speciosus_%281%29.jpg',
  },
  {
    id: 'weeping-boer-bean',
    commonName: 'Weeping Boer-bean',
    afrikaansName: 'Boerboon',
    scientificName: 'Schotia brachypetala',
    category: 'Trees',
    regions: ['potch'],
    bloomSeason: 'Spring (September–November)',
    funFact: 'Also nicknamed the "drunk parrot tree" — its flowers produce so much nectar that birds feeding on it can be seen dripping and giddy.',
    whereFound: 'Bushveld and riverine woodland across the northern and eastern interior of South Africa.',
    careTips: 'Full sun, well-drained soil, drought-tolerant once established, a superb shade and bird tree.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Schotia_brachypetala_-_%27Drunk_Parrot_Tree%27_%282941797784%29.jpg/500px-Schotia_brachypetala_-_%27Drunk_Parrot_Tree%27_%282941797784%29.jpg',
  },
  {
    id: 'buchu',
    commonName: 'Buchu',
    afrikaansName: 'Boegoe',
    scientificName: 'Agathosma betulina',
    category: 'Indigenous',
    regions: ['capetown'],
    bloomSeason: 'Spring, small white-pink star flowers',
    funFact: 'Used medicinally by the Khoi for centuries and still a staple of South African herbal medicine — its oil has a sharp, blackcurrant-like scent.',
    whereFound: 'Mountain fynbos of the Cederberg and Western Cape mountains.',
    careTips: 'Full sun, acidic well-drained soil, likes a cool root run — mulch to keep roots cool in summer.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/9/92/Agathosma_betulina_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-020.jpg',
  },
  {
    id: 'rooibos',
    commonName: 'Rooibos',
    afrikaansName: 'Rooibos',
    scientificName: 'Aspalathus linearis',
    category: 'Indigenous',
    regions: ['capetown'],
    bloomSeason: 'Spring, small yellow pea-like flowers',
    funFact: 'Grows naturally almost nowhere else on Earth except the Cederberg — every cup of rooibos tea starts with this one Cape shrub.',
    whereFound: 'Sandstone slopes of the Cederberg mountains in the Western Cape.',
    careTips: 'Full sun, sandy acidic soil, very drought-tolerant but notoriously fussy to grow outside its native Cederberg soil.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Rooibos_geschnitten.jpg/500px-Rooibos_geschnitten.jpg',
  },
  {
    id: 'cancer-bush',
    commonName: 'Cancer Bush',
    afrikaansName: 'Kankerbos',
    scientificName: 'Lessertia frutescens',
    category: 'Indigenous',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Spring to summer, bright orange-red flowers',
    funFact: 'One of the most famous plants in traditional South African medicine, historically used to treat all manner of ailments despite the misleadingly narrow name.',
    whereFound: 'Dry, disturbed ground right across South Africa, from the Karoo to the Highveld.',
    careTips: 'Full sun, well-drained soil, very drought-tolerant, self-seeds readily once established.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Lessertia_frutescens_1DS-II_5142.jpg/500px-Lessertia_frutescens_1DS-II_5142.jpg',
  },
  {
    id: 'african-wormwood',
    commonName: 'African Wormwood',
    afrikaansName: 'Wilde-als',
    scientificName: 'Artemisia afra',
    category: 'Indigenous',
    regions: ['potch', 'capetown'],
    bloomSeason: 'Autumn, small inconspicuous flowers',
    funFact: 'Probably South Africa’s best-known indigenous medicinal herb — a sprig brewed as a bitter tea is a household remedy for coughs and colds.',
    whereFound: 'Grassland and rocky slopes right across South Africa.',
    careTips: 'Full sun, tolerant of poor soil and drought, cut back hard after flowering to keep it neat.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Artemisia_afra_07102003_Afrique_du_sud_3.jpg/500px-Artemisia_afra_07102003_Afrique_du_sud_3.jpg',
  },
  {
    id: 'milkwood',
    commonName: 'Milkwood',
    afrikaansName: 'Melkhout',
    scientificName: 'Sideroxylon inerme',
    category: 'Trees',
    regions: ['capetown'],
    bloomSeason: 'Summer, small fragrant flowers',
    funFact: 'Protected by law in South Africa — may not be cut down without a permit, thanks partly to the famous Post Office Tree milkwood in Mossel Bay.',
    whereFound: 'Coastal forest and dunes along the Cape and southern coastlines.',
    careTips: 'Full sun to part shade, tolerant of wind and salt spray, slow-growing and very long-lived.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Sideroxylon_inerme_-_Milkwood_-_Cape_Town_6.JPG/500px-Sideroxylon_inerme_-_Milkwood_-_Cape_Town_6.JPG',
  },
  {
    id: 'sour-fig',
    commonName: 'Sour Fig',
    afrikaansName: 'Suurvy',
    scientificName: 'Carpobrotus edulis',
    category: 'Succulents',
    regions: ['capetown'],
    bloomSeason: 'Spring, large yellow or pink daisy-like flowers',
    funFact: 'Its tangy fruit has been eaten and made into jam by Cape communities for generations — a classic dune-stabilising groundcover.',
    whereFound: 'Coastal dunes and rocky slopes right along the Cape coastline.',
    careTips: 'Full sun, sandy well-drained soil, extremely drought- and salt-tolerant — a tough, spreading groundcover.',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Hottentot_Fig_-_Flowering.jpg/500px-Hottentot_Fig_-_Flowering.jpg',
  },
]

export const PLANT_EXPLORE_FILTERS = [
  { id: 'all', label: 'All plants', test: () => true },
  { id: 'potch', label: 'Near Potchefstroom', test: (p) => p.regions.includes('potch') },
  { id: 'capetown', label: 'Near Cape Town', test: (p) => p.regions.includes('capetown') },
  { id: 'flowers', label: 'Flowers', test: (p) => p.category === 'Flowers' },
  { id: 'trees', label: 'Trees', test: (p) => p.category === 'Trees' },
  { id: 'succulents', label: 'Succulents', test: (p) => p.category === 'Succulents' },
  { id: 'fynbos', label: 'Fynbos', test: (p) => p.category === 'Fynbos' },
  { id: 'garden', label: 'Garden Plants', test: (p) => p.category === 'Garden Plants' },
  { id: 'indigenous', label: 'Indigenous', test: (p) => p.category === 'Indigenous' },
]

const PLANT_CATEGORY_EMOJI = {
  Flowers: '🌸',
  Trees: '🌳',
  Succulents: '🌵',
  Fynbos: '🏵️',
  'Garden Plants': '🌿',
  Indigenous: '🍃',
}

export function plantCategoryEmoji(category) {
  return PLANT_CATEGORY_EMOJI[category] || '🌿'
}

function hash(str) {
  let h = 2166136261
  for (let i = 0; i < str.length; i += 1) {
    h ^= str.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return h >>> 0
}

// Same Monday-based weekly reseed as the bird watch-list (birdExplore.js) —
// the same set holds all week, then a fresh set appears every Monday.
function weekSeed(date) {
  const dayNumber = Math.floor(
    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86400000,
  )
  return Math.floor((dayNumber + 3) / 7)
}

function weeklyPlantWatchList(pool, date, count) {
  if (!pool.length) return []
  const seed = weekSeed(date)
  return pool
    .map((plant, i) => ({ plant, k: hash(`plant-${seed}-${plant.id}-${i}`) }))
    .sort((a, b) => a.k - b.k)
    .slice(0, Math.min(count, pool.length))
    .map((o) => o.plant)
}

export function plantsNearPotchThisWeek(date = new Date(), count = 7) {
  return weeklyPlantWatchList(
    SA_PLANT_LIBRARY.filter((p) => p.regions.includes('potch')),
    date,
    count,
  )
}

export function plantsNearCapeTownThisWeek(date = new Date(), count = 7) {
  return weeklyPlantWatchList(
    SA_PLANT_LIBRARY.filter((p) => p.regions.includes('capetown')),
    date,
    count,
  )
}

export function findPlantById(id) {
  return SA_PLANT_LIBRARY.find((p) => p.id === id) || null
}
